import Header from "@/components/header";
import "./globals.css";

export const metadata = {
  title: "Trello App",
  description: "Generated by create next app and shadcn/ui",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className="flex flex-col min-h-screen bg-[#f5f6f8]">
        <Header />
        {children}
      </body>
    </html>
  );
}
